kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  labels:
    component: nodejs
    tier: app
spec:
  replicas: 2
  selector:
    matchLables:
      component: nodejs
      tier: app
  template:
    metadata: 
      name: app
      labels:
        component: nodejs
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80 




