apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  selector: 
    component: nodejs
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31638
  